spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service-auth
              uri: http://user-service:8081
              predicates:
                - Path=/api/auth/**

            - id: user-service-users
              uri: http://user-service:8081
              predicates:
                - Path=/api/users/**

            - id: catalog-service
              uri: http://catalog-service:8082
              predicates:
                - Path=/api/catalog/**

            - id: deal-payment-service
              uri: http://deal-payment-service:8083
              predicates:
                - Path=/api/deals/**

server:
  port: 8080