server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service-auth
              uri: http://localhost:8081
              predicates:
                  - Path=/api/auth/**

            - id: user-service-users
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**

            - id: catalog-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/catalog/**

            - id: deal-payment-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/deals/**

            - id: comm-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/chats/**
                - Path=/api/messages/**
                - Path=/api/reviews/**
                - Path=/api/complaints/**

            - id: notif-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info